name: new_boulevard
description: A new Flutter project.



publish_to: 'none' 


version: 1.0.0+3

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.3+1
  flutter_svg: ^1.0.3
  http: ^0.13.4
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  video_player: ^2.4.5
  cached_network_image: ^3.2.3
  share_plus: ^4.0.10
  url_launcher: ^6.1.4
  google_maps_flutter:
  flutter_video_info: ^1.2.0
  geocoding:
  location:
  image_size_getter: ^2.1.2
  wakelock: ^0.6.2
  geolocator: ^9.0.2
  flutter_swiper_view: ^1.1.8
  another_flushbar: ^1.12.29
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5
  flutter_cache_manager: ^3.3.0
  chewie: ^1.4.0
  cache_manager: ^1.0.0+4
  cached_video_player: ^2.0.4










dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
 

flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
