name: new_boulevard
description: A new Flutter project.



publish_to: 'none' 


version: 1.0.0+3

environment:
  sdk: '>=2.18.2 <3.0.0'

##^2.4.5
##^2.4.9+1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg:
  http: ^1.1.0
  shared_preferences: ^2.2.1
  image_picker: ^0.8.7+4
  video_player:
  cached_network_image: ^3.2.3
  share_plus: ^4.0.10
  url_launcher: ^6.1.14
  google_maps_flutter: ^2.5.0
  flutter_video_info: ^1.3.1
  geocoding: ^2.1.0
  #location:
  image_size_getter: ^2.1.2
  wakelock_plus: ^1.1.1
  geolocator: ^10.0.1
  flutter_swiper_view: ^1.1.8
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.6
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5
  video_cached_player:
  dio: ^5.3.2
  percent_indicator: ^4.2.3
  flutter_html:













dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/v2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21





flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
