name: new_boulevard
description: A new Flutter project.



publish_to: 'none' 


version: 1.0.0+3

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  http:
  shared_preferences:
  image_picker:
  video_player:
  cached_network_image:
  share_plus:
  url_launcher:
  google_maps_flutter:
  flutter_video_info:
  geocoding:
  #location:
  image_size_getter:
  wakelock:
  geolocator:
  flutter_swiper_view:
  another_flushbar:
  cupertino_icons:
  loading_animation_widget:
  provider:
  video_cached_player:
  dio:
  percent_indicator:
  flutter_html:













dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/v2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21





flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
