import 'package:new_boulevard/models/detalies.dart';
import 'package:new_boulevard/models/special_ads.dart';
import 'package:new_boulevard/models/story.dart';
import 'package:new_boulevard/models/user.dart';

class Autogenerated {
  bool? status;
  int? code;
  String? message;
  Advertiser? advertiser;
  List<AdvertiserADs>? advertiserADs;

  Autogenerated(
      {this.status,
        this.code,
        this.message,
        this.advertiser,
        this.advertiserADs});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    advertiser = json['advertiser'] != null
        ? new Advertiser.fromJson(json['advertiser'])
        : null;
    if (json['advertiserADs'] != null) {
      advertiserADs = <AdvertiserADs>[];
      json['advertiserADs'].forEach((v) {
        advertiserADs!.add(new AdvertiserADs.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.advertiser != null) {
      data['advertiser'] = this.advertiser!.toJson();
    }
    if (this.advertiserADs != null) {
      data['advertiserADs'] =
          this.advertiserADs!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class AdvertiserADs {
  int? id;
  int? adTypeId;
  int? userId;
  int? categoryId;
  int? follow_me_count;
  int? cityId;
  String? image;
  String? twitter;
  String? instagram;
  String? whatsapp;
  String? email;
  String? facebook;
  String? storeUrl;
  String? status;
  String? paymentURL;
  String? name;
  String? details;
  String? mobile;
  String? website;
  AdType? adType;
  Category? category;
  City? city;
  List<story1>? adImages;
  List<story1>? adVideos;


  AdvertiserADs();

  AdvertiserADs.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    adTypeId = json['ad_type_id'];
    paymentURL = json['paymentURL'];
    userId = json['user_id'];
    categoryId = json['category_id'];
    cityId = json['city_id'];
    image = json['image'];
    facebook = json['facebook'];
    whatsapp = json['whatsapp'];
    storeUrl = json['storeUrl'];
    twitter = json['twitter'];
    instagram = json['instagram'];
    mobile = json['mobile'];
    status = json['status'];
    website = json['website'];

    email = json['email'];
    name = json['name'];
    details = json['details'];
    follow_me_count = json['follow_me_count'];
    adType =
    json['ad_type'] != null ? new AdType.fromJson(json['ad_type']) : null;
    category = json['category'] != null
        ? new Category.fromJson(json['category'])
        : null;
    city = json['city'] != null ? new City.fromJson(json['city']) : null;;
    if (json['ad_images'] != null) {
      adImages = <story1>[];
      json['ad_images'].forEach((v) {
        adImages!.add(new story1.fromJson(v));
      });
    }
    // if (json['ad_videos'] != null) {
    //   adVideos = <AdVideos>[];
    //   json['ad_videos'].forEach((v) {
    //     adVideos!.add(new AdVideos.fromJson(v));
    //   });
    // }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['ad_type_id'] = this.adTypeId;
    data['user_id'] = this.userId;
    data['category_id'] = this.categoryId;
    data['city_id'] = this.cityId;
    data['storeUrl'] = this.storeUrl;
    data['follow_me_count'] = this.follow_me_count;
    data['mobile'] = this.mobile;
    data['website'] = this.website;

    data['facebook'] = this.facebook;
    data['instagram'] = this.instagram;
    data['twitter'] = this.twitter;
    data['whatsapp'] = this.whatsapp;
    data['email'] = this.email;
    data['paymentURL'] = this.paymentURL;

    data['image'] = this.image;
    data['status'] = this.status;
    data['name'] = this.name;
    data['details'] = this.details;
    if (this.adType != null) {
      data['ad_type'] = this.adType!.toJson();
    }
    if (this.category != null) {
      data['category'] = this.category!.toJson();
    }
    if (this.city != null) {
      data['city'] = this.city!.toJson();
    }
    if (this.adImages != null) {
      data['ad_images'] = this.adImages!.map((v) => v.toJson()).toList();
    }
    // if (this.adVideos != null) {
    //   data['ad_videos'] = this.adVideos!.map((v) => v.toJson()).toList();
    // }
    return data;
  }
}
class AdType {
  int? id;
  String? type;
  int? daysCount;
  int? price;
  String? name;
  String? details;

  AdType(
      {this.id,
        this.type,
        this.daysCount,
        this.price,
        this.name,
        this.details});

  AdType.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    type = json['type'];
    daysCount = json['days_count'];
    price = json['price'];
    name = json['name'];
    details = json['details'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['type'] = this.type;
    data['days_count'] = this.daysCount;
    data['price'] = this.price;
    data['name'] = this.name;
    data['details'] = this.details;
    return data;
  }
}


class ListStory{
  List<story1>? ad;

ListStory({ this.ad});
}



class Data{
  List<story1>? ad;
  List<int>? countitem;

  Data({ this.ad});
}
class INFO{
  List<Ads>? info;
  INFO({this.info});


}

class story1 {
  int? id;
  int? adId;
  String? type;
  String? file;
  String? createdAt;
  String? duration;
  int? height;
  int? width;


  story1();

  story1.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    adId = json['ad_id'];
    type = json['type'];
    file = json['file'];
    createdAt = json['created_at'];
    duration = json['duration'];
    height = json['height'];
    width = json['width'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['ad_id'] = this.adId;
    data['type'] = this.type;
    data['file'] = this.file;
    data['created_at'] = this.createdAt;
    data['duration'] = this.duration;
    data['height'] = this.height;
    data['width'] = this.width;
    return data;
  }
}


class Doit{
  Ads ad =Ads();
 List <story1> item;
  Doit({required this.item,required this.ad});

}





