import 'package:new_boulevard/models/detalies.dart';
import 'package:new_boulevard/models/special_ads.dart';
import 'package:new_boulevard/models/story.dart';
import 'package:new_boulevard/models/user.dart';
import 'package:video_cached_player/video_cached_player.dart';

class Autogenerated {
  bool? status;
  int? code;
  String? message;
  Advertiser? advertiser;
  List<AdvertiserADs>? advertiserADs;

  Autogenerated(
      {this.status,
      this.code,
      this.message,
      this.advertiser,
      this.advertiserADs});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    advertiser = json['advertiser'] != null
        ? Advertiser.fromJson(json['advertiser'])
        : null;
    if (json['advertiserADs'] != null) {
      advertiserADs = <AdvertiserADs>[];
      json['advertiserADs'].forEach((v) {
        advertiserADs!.add(AdvertiserADs.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    if (advertiser != null) {
      data['advertiser'] = advertiser!.toJson();
    }
    if (advertiserADs != null) {
      data['advertiserADs'] = advertiserADs!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class AdvertiserADs {
  int? id;
  String? adTypeId;
  String? userId;
  String? categoryId;
  int? follow_me_count;
  String? cityId;
  String? image;
  String? twitter;
  String? instagram;
  String? whatsapp;
  String? email;
  String? facebook;
  String? storeUrl;
  String? status;
  String? paymentURL;
  String? name;
  String? details;
  String? mobile;
  String? website;
  AdType? adType;
  Category? category;
  City? city;
  List<story1>? adImages;
  List<story1>? adVideos;
  AdvertiserADs();

  AdvertiserADs.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    adTypeId = json['ad_type_id'];
    paymentURL = json['paymentURL'];
    userId = json['user_id'];
    categoryId = json['category_id'];
    cityId = json['city_id'];
    image = json['image'];
    facebook = json['facebook'];
    whatsapp = json['whatsapp'];
    storeUrl = json['storeUrl'];
    twitter = json['twitter'];
    instagram = json['instagram'];
    mobile = json['mobile'];
    status = json['status'];
    website = json['website'];

    email = json['email'];
    name = json['name'];
    details = json['details'];
    follow_me_count = json['follow_me_count'];
    adType = json['ad_type'] != null ? AdType.fromJson(json['ad_type']) : null;
    category =
        json['category'] != null ? Category.fromJson(json['category']) : null;
    city = json['city'] != null ? City.fromJson(json['city']) : null;
    if (json['ad_images'] != null) {
      adImages = <story1>[];
      json['ad_images'].forEach((v) {
        adImages!.add(story1.fromJson(v));
      });
    }
    // if (json['ad_videos'] != null) {
    //   adVideos = <AdVideos>[];
    //   json['ad_videos'].forEach((v) {
    //     adVideos!.add(new AdVideos.fromJson(v));
    //   });
    // }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['ad_type_id'] = adTypeId;
    data['user_id'] = userId;
    data['category_id'] = categoryId;
    data['city_id'] = cityId;
    data['storeUrl'] = storeUrl;
    data['follow_me_count'] = follow_me_count;
    data['mobile'] = mobile;
    data['website'] = website;

    data['facebook'] = facebook;
    data['instagram'] = instagram;
    data['twitter'] = twitter;
    data['whatsapp'] = whatsapp;
    data['email'] = email;
    data['paymentURL'] = paymentURL;

    data['image'] = image;
    data['status'] = status;
    data['name'] = name;
    data['details'] = details;
    if (adType != null) {
      data['ad_type'] = adType!.toJson();
    }
    if (category != null) {
      data['category'] = category!.toJson();
    }
    if (city != null) {
      data['city'] = city!.toJson();
    }
    if (adImages != null) {
      data['ad_images'] = adImages!.map((v) => v.toJson()).toList();
    }
    // if (this.adVideos != null) {
    //   data['ad_videos'] = this.adVideos!.map((v) => v.toJson()).toList();
    // }
    return data;
  }
}

class AdType {
  int? id;
  String? type;
  var daysCount;
  int? price;
  String? name;
  String? details;

  AdType(
      {this.id,
      this.type,
      this.daysCount,
      this.price,
      this.name,
      this.details});

  AdType.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    type = json['type'];
    daysCount = json['days_count'];
    price = json['price'];
    name = json['name'];
    details = json['details'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['days_count'] = daysCount;
    data['price'] = price;
    data['name'] = name;
    data['details'] = details;
    return data;
  }
}
class VideoType{
  List<CachedVideoPlayerController>? controllerVideo ;
  int? page;
 List<int>? lenght;
  VideoType({this.controllerVideo,this.page,this.lenght});
}
class ListStory {
  List<story1>? ad;
  int? page;
  int? lengthad;

  ListStory({this.ad, this.page, this.lengthad,});
}




class story1 {
  int? id;
  String? type;
  String? file;
  String? createdAt;
  String? duration;
  String? height;
  String? width;

  story1();

  story1.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    type = json['type'];
    file = json['file'];
    createdAt = json['created_at'];
    duration = json['duration'];
    height = json['height'];
    width = json['width'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['file'] = file;
    data['created_at'] = createdAt;
    data['duration'] = duration;
    data['height'] = height;
    data['width'] = width;
    return data;
  }
}


