class Autogenerated {
  bool? status;
  int? code;
  String? message;
  List<Awards>? awards;

  Autogenerated({this.status, this.code, this.message, this.awards});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    if (json['awards'] != null) {
      awards = <Awards>[];
      json['awards'].forEach((v) {
        awards!.add(new Awards.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.awards != null) {
      data['awards'] = this.awards!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Awards {
  int? id;
  int? pointsCount;
  String? prizeDrawDate;
  String? image;
  String? status;
  int? isRequested;
  String? name;
  String? details;

  Awards(
      {this.id,
        this.pointsCount,
        this.prizeDrawDate,
        this.image,
        this.status,
        this.isRequested,
        this.name,
        this.details});

  Awards.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    pointsCount = json['points_count'];
    prizeDrawDate = json['prize_draw_date'];
    image = json['image'];
    status = json['status'];
    isRequested = json['is_requested'];
    name = json['name'];
    details = json['details'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['points_count'] = this.pointsCount;
    data['prize_draw_date'] = this.prizeDrawDate;
    data['image'] = this.image;
    data['status'] = this.status;
    data['is_requested'] = this.isRequested;
    data['name'] = this.name;
    data['details'] = this.details;
    return data;
  }
}