import 'package:new_boulevard/models/ads.dart';
import 'package:new_boulevard/models/special_ads.dart';
import 'package:new_boulevard/models/story.dart';
import 'package:new_boulevard/models/user.dart';

class Autogenerated {
  bool? status;
  int? code;
  String? message;
  List<Ads>? ads;

  Autogenerated({this.status, this.code, this.message, this.ads});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    if (json['ads'] != null) {
      ads = <Ads>[];
      json['ads'].forEach((v) {
        ads!.add(Ads.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    if (ads != null) {
      data['ads'] = ads!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Ads {
  int? id;
  String? adTypeId;
  String? userId;
  String? categoryId;
  String? cityId;
  String? image;
  String? ad_paid;
  String? status;
  String? latitude;
  String? longitude;
  String? store_url;
  String? facebook;
  String? whatsapp;
  String? instagram;
  String? paymentURL;
  String? twitter;
  String? name;
  String? details;
  Advertiser? advertiser;
  AdType? adType;
  Category? category;
  City? city;
  List<story1>? adImages;
  List<story1>? adVideos;

  Ads();

  Ads.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    adTypeId = json['ad_type_id'];
    userId = json['user_id'];
    categoryId = json['category_id'];
    cityId = json['city_id'];
    image = json['image'];
    ad_paid = json['ad_paid'];

    store_url = json['store_url'];
    facebook = json['facebook'];
    twitter = json['twitter'];
    instagram = json['instagram'];
    whatsapp = json['whatsapp'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    paymentURL = json['paymentURL'];

    status = json['status'];
    name = json['name'];
    details = json['details'];
    advertiser = json['advertiser'] != null
        ? Advertiser.fromJson(json['advertiser'])
        : null;
    adType = json['ad_type'] != null ? AdType.fromJson(json['ad_type']) : null;
    category =
        json['category'] != null ? Category.fromJson(json['category']) : null;
    city = json['city'] != null ? City.fromJson(json['city']) : null;
    if (json['ad_images'] != null) {
      adImages = <story1>[];
      json['ad_images'].forEach((v) {
        adImages!.add(story1.fromJson(v));
      });
    }
    if (json['ad_videos'] != null) {
      adVideos = <story1>[];
      json['ad_videos'].forEach((v) {
        adVideos!.add(story1.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['ad_type_id'] = adTypeId;
    data['user_id'] = userId;
    data['category_id'] = categoryId;
    data['city_id'] = cityId;
    data['image'] = image;
    data['status'] = status;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['paymentURL'] = paymentURL;
    data['ad_paid'] = ad_paid;
    data['store_url'] = store_url;
    data['facebook'] = facebook;
    data['twitter'] = twitter;
    data['instagram'] = instagram;
    data['whatsapp'] = whatsapp;
    data['name'] = name;
    data['details'] = details;
    if (advertiser != null) {
      data['advertiser'] = advertiser!.toJson();
    }
    if (adType != null) {
      data['ad_type'] = adType!.toJson();
    }
    if (category != null) {
      data['category'] = category!.toJson();
    }
    if (city != null) {
      data['city'] = city!.toJson();
    }
    if (adImages != null) {
      data['ad_images'] = adImages!.map((v) => v.toJson()).toList();
    }
    if (adVideos != null) {
      data['ad_videos'] = adVideos!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
