class Autogenerated {
  bool? status;
  int? code;
  String? message;
  List<MyFollowers>? myFollowers;

  Autogenerated({this.status, this.code, this.message, this.myFollowers});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    if (json['myFollowers'] != null) {
      myFollowers = <MyFollowers>[];
      json['myFollowers'].forEach((v) {
        myFollowers!.add(MyFollowers.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    if (myFollowers != null) {
      data['myFollowers'] = myFollowers!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class MyFollowers {
  int? id;
  String? name;
  String? imageProfile;

  MyFollowers({this.id, this.name, this.imageProfile});

  MyFollowers.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    imageProfile = json['image_profile'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image_profile'] = imageProfile;
    return data;
  }
}
