import 'detalies.dart';

class Autogenerated {
  bool? status;
  int? code;
  String? message;
  List<MyFollowings>? myFollowings;

  Autogenerated({this.status, this.code, this.message, this.myFollowings});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    if (json['myFollowings'] != null) {
      myFollowings = <MyFollowings>[];
      json['myFollowings'].forEach((v) {
        myFollowings!.add(MyFollowings.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    if (myFollowings != null) {
      data['myFollowings'] = myFollowings!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class MyFollowings {
  String? id;
  String? name;
  String? imageProfile;
  int? followMeCount;
  List<Ads>? ads;

  MyFollowings();

  MyFollowings.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    imageProfile = json['image_profile'];
    followMeCount = json['follow_me_count'];
    if (json['ads'] != null) {
      ads = <Ads>[];
      json['ads'].forEach((v) {
        ads!.add(Ads.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image_profile'] = imageProfile;
    data['follow_me_count'] = followMeCount;
    if (ads != null) {
      data['ads'] = ads!.map((v) => v.toJson()).toList();
    }

    return data;
  }
}
