class Autogenerated {
  bool? status;
  int? code;
  String? message;
  Settings? settings;

  Autogenerated({this.status, this.code, this.message, this.settings});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    settings =
        json['settings'] != null ? Settings.fromJson(json['settings']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    if (settings != null) {
      data['settings'] = settings!.toJson();
    }
    return data;
  }
}

class Settings {
  int? id;
  String? url;
  String? whatsapp;
  String? linked_in;
  String? instagram;
  String? description;
  String? advertisingPolicies;
  List<Banners>? banners;

  Settings();

  Settings.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    url = json['url'];
    linked_in = json['linked_in'];
    instagram = json['instagram'];
    whatsapp = json['whatsapp'];
    advertisingPolicies = json['advertisingPolicies'];
    description = json['description'];
     if (json['banners'] != null) {
      banners = <Banners>[];
      json['banners'].forEach((v) {
        banners!.add(new Banners.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['url'] = url;
    data['linked_in'] = linked_in;
    data['instagram'] = instagram;
    data['whatsapp'] = whatsapp;
    data['advertisingPolicies'] = advertisingPolicies;
    data['whatsapp'] = whatsapp;
     if (this.banners != null) {
      data['banners'] = this.banners!.map((v) => v.toJson()).toList();
    }
    data['description'] = description;
    return data;
  }
}

class Banners {
  int? id;
  String? image;


  Banners({this.id, this.image, });

  Banners.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    image = json['image'];

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['image'] = this.image;
    return data;
  }
}


