import 'package:new_boulevard/models/story.dart';
import 'package:new_boulevard/models/user.dart';

import 'ads.dart';

class Autogenerated {
  bool? status;
  int? code;
  String? message;
  List<SpecialAds>? specialAds;

  Autogenerated({this.status, this.code, this.message, this.specialAds});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    if (json['special_ads'] != null) {
      specialAds = <SpecialAds>[];
      json['special_ads'].forEach((v) {
        specialAds!.add(new SpecialAds.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.specialAds != null) {
      data['special_ads'] = this.specialAds!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SpecialAds {
  int? id;
  int? adTypeId;
  int? userId;
  int? categoryId;
  int? cityId;
  String? image;
  String? status;
  String? name;
  String? details;
  Advertiser? advertiser;
  AdType? adType;
  Category? category;
  City? city;
  List<story1>? adImages;

  SpecialAds();

  SpecialAds.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    adTypeId = json['ad_type_id'];
    userId = json['user_id'];
    categoryId = json['category_id'];
    cityId = json['city_id'];
    image = json['image'];
    status = json['status'];
    name = json['name'];
    details = json['details'];
    advertiser = json['advertiser'] != null ? new Advertiser.fromJson(json['advertiser']) : null;
    adType =
    json['ad_type'] != null ? new AdType.fromJson(json['ad_type']) : null;
    category = json['category'] != null
        ? new Category.fromJson(json['category'])
        : null;
    city = json['city'] != null ? new City.fromJson(json['city']) : null;
    if (json['ad_images'] != null) {
      adImages = <story1>[];
      json['ad_images'].forEach((v) {
        adImages!.add(new story1.fromJson(v));
      });
    }

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['ad_type_id'] = this.adTypeId;
    data['user_id'] = this.userId;
    data['category_id'] = this.categoryId;
    data['city_id'] = this.cityId;
    data['image'] = this.image;
    data['status'] = this.status;
    data['name'] = this.name;
    data['details'] = this.details;
    if (this.advertiser != null) {
      data['advertiser'] = this.advertiser!.toJson();
    }
    if (this.adType != null) {
      data['ad_type'] = this.adType!.toJson();
    }
    if (this.category != null) {
      data['category'] = this.category!.toJson();
    }
    if (this.city != null) {
      data['city'] = this.city!.toJson();
    }
    if (this.adImages != null) {
      data['ad_images'] = this.adImages!.map((v) => v.toJson()).toList();
    }

    return data;
  }
}







