import 'package:new_boulevard/models/story.dart';
import 'package:new_boulevard/models/user.dart';

import 'ads.dart';

class Autogenerated {
  bool? status;
  int? code;
  String? message;
  List<SpecialAds>? specialAds;

  Autogenerated({this.status, this.code, this.message, this.specialAds});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    if (json['special_ads'] != null) {
      specialAds = <SpecialAds>[];
      json['special_ads'].forEach((v) {
        specialAds!.add(SpecialAds.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    if (specialAds != null) {
      data['special_ads'] = specialAds!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SpecialAds {
  int? id;
  String? image;
  String? name;
  Advertiser? advertiser;



  SpecialAds();

  SpecialAds.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    image = json['image'];
    name = json['name'];
    advertiser = json['advertiser'] != null
        ? Advertiser.fromJson(json['advertiser'])
        : null;

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['image'] = image;
    data['name'] = name;
    if (advertiser != null) {
      data['advertiser'] = advertiser!.toJson();
    }

    return data;
  }
}
