import 'package:new_boulevard/models/ads.dart';
import 'package:new_boulevard/models/categories.dart';
import 'package:new_boulevard/models/special_ads.dart';
import 'package:new_boulevard/models/user.dart';

class Autogenerated {
  bool? status;
  int? code;
  String? message;
  List<Stores>? stores;
  List<SpecialAds>? specialAds;
  List<Categories>? categories;

  Autogenerated(
      {this.status,
        this.code,
        this.message,
        this.stores,
        this.specialAds,
        this.categories});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    if (json['stores'] != null) {
      stores = <Stores>[];
      json['stores'].forEach((v) {
        stores!.add(new Stores.fromJson(v));
      });
    }
    if (json['special_ads'] != null) {
      specialAds = <SpecialAds>[];
      json['special_ads'].forEach((v) {
        specialAds!.add(new SpecialAds.fromJson(v));
      });
    }
    if (json['categories'] != null) {
      categories = <Categories>[];
      json['categories'].forEach((v) {
        categories!.add(new Categories.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.stores != null) {
      data['stores'] = this.stores!.map((v) => v.toJson()).toList();
    }
    if (this.specialAds != null) {
      data['special_ads'] = this.specialAds!.map((v) => v.toJson()).toList();
    }
    if (this.categories != null) {
      data['categories'] = this.categories!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Stores {
  int? id;
  int? adTypeId;
  int? userId;
  int? categoryId;
  int? cityId;
  String? image;
  String? status;
  String? name;
  String? details;
  AdType? adType;
  Category? category;
  City? city;
  List<story1>? adImages;
  Advertiser? advertiser;
  List<story1>? adVideos;

  Stores();

  Stores.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    adTypeId = json['ad_type_id'];
    userId = json['user_id'];
    categoryId = json['category_id'];
    cityId = json['city_id'];
    image = json['image'];
    status = json['status'];
    name = json['name'];
    details = json['details'];
    adType =
    json['ad_type'] != null ? new AdType.fromJson(json['ad_type']) : null;
    category = json['category'] != null
        ? new Category.fromJson(json['category'])
        : null;
    city = json['city'] != null ? new City.fromJson(json['city']) : null;
    if (json['ad_images'] != null) {
      adImages = <story1>[];
      json['ad_images'].forEach((v) {
        adImages!.add(new story1.fromJson(v));
      });
    }
    if (json['ad_videos'] != null) {
      adVideos = <story1>[];
      json['ad_videos'].forEach((v) {
        adVideos!.add(new story1.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['ad_type_id'] = this.adTypeId;
    data['user_id'] = this.userId;
    data['category_id'] = this.categoryId;
    data['city_id'] = this.cityId;
    data['image'] = this.image;
    data['status'] = this.status;
    data['name'] = this.name;
    data['details'] = this.details;
    if (this.adType != null) {
      data['ad_type'] = this.adType!.toJson();
    }
    if (this.category != null) {
      data['category'] = this.category!.toJson();
    }
    if (this.city != null) {
      data['city'] = this.city!.toJson();
    }
    if (this.adImages != null) {
      data['ad_images'] = this.adImages!.map((v) => v.toJson()).toList();
    }
    if (this.adVideos != null) {
      data['ad_videos'] = this.adVideos!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
class Category {
  int? id;
  String? image;
  String? name;

  Category({this.id, this.image, this.name});

  Category.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    image = json['image'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['image'] = this.image;
    data['name'] = this.name;
    return data;
  }
}



