class Autogenerated {
  bool? status;
  int? code;
  String? message;
  User? user;
  List<Followers>? followers;

  Autogenerated({
    this.status,
    this.code,
    this.message,
    this.user,
    this.followers,
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    user = json['user'] != null ? User.fromJson(json['user']) : null;
    if (json['followers'] != null) {
      followers = <Followers>[];
      json['followers'].forEach((v) {
        followers!.add(Followers.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    if (followers != null) {
      data['followers'] = followers!.map((v) => v.toJson()).toList();
    }

    return data;
  }
}

class User {
  late int id;
  int? cityId;
  late String name;
  String? commercialActivities;
  late String mobile;
  late String email;
  String? rememberToken;
  late String type;
  String? status;
  String? createdAt;
  late String accessToken;
  late String password;
  City? city;
  int? pointsCount;
  int? new_notifications;
  String? imageProfile;
  int? followMeCount;
  String? facebook;
  String? whatsapp;
  String? instagram;
  String? twitter;
  String? website;

  User();

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    pointsCount = json['points_count'];
    cityId = json['city_id'];
    name = json['name'];
    commercialActivities = json['commercial_activities'];
    mobile = json['mobile'];
    email = json['email'];
    facebook = json['facebook'];
    whatsapp = json['whatsapp'];
    instagram = json['instagram'];
    twitter = json['twitter'];
    website = json['website'];
    new_notifications = json['new_notifications'];

    rememberToken = json['remember_token'];
    imageProfile = json['image_profile'];
    type = json['type'];
    status = json['status'];
    createdAt = json['created_at'];
    accessToken = json['access_token'];
    followMeCount = json['follow_me_count'];
    city = json['city'] != null ? City.fromJson(json['city']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['points_count'] = pointsCount;
    data['city_id'] = cityId;
    data['name'] = name;
    data['commercial_activities'] = commercialActivities;
    data['mobile'] = mobile;
    data['email'] = email;
    data['remember_token'] = rememberToken;
    data['image_profile'] = imageProfile;
    data['facebook'] = facebook;
    data['whatsapp'] = whatsapp;
    data['instagram'] = instagram;
    data['twitter'] = twitter;
    data['type'] = type;
    data['status'] = status;
    data['new_notifications'] = new_notifications;
    data['created_at'] = createdAt;
    data['access_token'] = accessToken;
    data['follow_me_count'] = followMeCount;
    data['website'] = website;
    if (city != null) {
      data['city'] = city!.toJson();
    }
    return data;
  }
}

class City {
  int? id;
  int? countryId;
  String? status;
  String? createdAt;
  String? name;

  City();

  City.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    countryId = json['country_id'];
    status = json['status'];
    createdAt = json['created_at'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['country_id'] = countryId;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['name'] = name;
    return data;
  }
}

class Followers {
  int? id;
  int? followerId;
  int? followedId;
  String? createdAt;

  Advertiser? advertiser;
  Follower? follower;

  Followers.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    followerId = json['follower_id'];
    followedId = json['followed_id'];
    createdAt = json['created_at'];

    advertiser = json['advertiser'] != null
        ? Advertiser.fromJson(json['advertiser'])
        : null;
    follower =
        json['follower'] != null ? Follower.fromJson(json['follower']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['follower_id'] = followerId;
    data['followed_id'] = followedId;
    data['created_at'] = createdAt;

    if (advertiser != null) {
      data['advertiser'] = advertiser!.toJson();
    }
    if (follower != null) {
      data['follower'] = follower!.toJson();
    }
    return data;
  }
}

class Advertiser {
  int? id;
  int? pointsCount;
  int? cityId;
  String? name;
  String? commercialActivities;
  String? mobile;
  String? website;
  String? email;
  String? twitter;
  String? instagram;
  String? whatsapp;
  String? facebook;
  String? latitude;
  String? longitude;
  dynamic rememberToken;
  String? imageProfile;
  String? type;
  String? status;
  String? createdAt;
  int? followMeCount;
  City? city;
  Advertiser();

  Advertiser.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    pointsCount = json['points_count'];
    cityId = json['city_id'];
    name = json['name'];
    commercialActivities = json['commercial_activities'];
    mobile = json['mobile'];
    email = json['email'];
    facebook = json['facebook'];
    whatsapp = json['whatsapp'];
    twitter = json['twitter'];
    instagram = json['instagram'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    rememberToken = json['remember_token'];
    imageProfile = json['image_profile'];
    type = json['type'];
    website = json['website'];
    status = json['status'];
    createdAt = json['created_at'];
    followMeCount = json['follow_me_count'];
    city = json['city'] != null ? City.fromJson(json['city']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['points_count'] = pointsCount;
    data['city_id'] = cityId;
    data['facebook'] = facebook;
    data['instagram'] = instagram;
    data['twitter'] = twitter;
    data['whatsapp'] = whatsapp;
    data['name'] = name;
    data['commercial_activities'] = commercialActivities;
    data['mobile'] = mobile;
    data['email'] = email;
    data['website'] = website;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['remember_token'] = rememberToken;
    data['image_profile'] = imageProfile;
    data['type'] = type;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['follow_me_count'] = followMeCount;
    if (city != null) {
      data['city'] = city!.toJson();
    }
    return data;
  }
}

class Follower {
  int? id;
  int? pointsCount;
  int? cityId;
  String? name;
  String? commercialActivities;
  String? mobile;
  String? email;
  dynamic latitude;
  dynamic longitude;
  dynamic rememberToken;
  String? imageProfile;
  String? type;
  String? status;
  String? createdAt;
  int? followMeCount;
  City? city;
  Follower();

  Follower.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    pointsCount = json['points_count'];
    cityId = json['city_id'];
    name = json['name'];
    commercialActivities = json['commercial_activities'];
    mobile = json['mobile'];
    email = json['email'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    rememberToken = json['remember_token'];
    imageProfile = json['image_profile'];
    type = json['type'];
    status = json['status'];
    createdAt = json['created_at'];
    followMeCount = json['follow_me_count'];
    city = json['city'] != null ? City.fromJson(json['city']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['points_count'] = pointsCount;
    data['city_id'] = cityId;
    data['name'] = name;
    data['commercial_activities'] = commercialActivities;
    data['mobile'] = mobile;
    data['email'] = email;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['remember_token'] = rememberToken;
    data['image_profile'] = imageProfile;
    data['type'] = type;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['follow_me_count'] = followMeCount;
    if (city != null) {
      data['city'] = city!.toJson();
    }
    return data;
  }
}
