class Autogenerated {
  bool? status;
  int? code;
  String? message;
  User? user;
  List<Followers>? followers;


  Autogenerated(
      {this.status,
        this.code,
        this.message,
        this.user,
        this.followers,
        });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
    if (json['followers'] != null) {
      followers = <Followers>[];
      json['followers'].forEach((v) {
        followers!.add(new Followers.fromJson(v));
      });
    }

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    if (this.followers != null) {
      data['followers'] = this.followers!.map((v) => v.toJson()).toList();
    }

    return data;
  }
}











class User {
  late int id;
  int? cityId;
  late String name;
  String? commercialActivities;
  late String mobile;
  late String email;
  String? rememberToken;
  late String type;
  String? status;
  String? createdAt;
  late  String accessToken;
  late String password;
  City? city;
  int? pointsCount;
  String? imageProfile;
  int? followMeCount;
  String? facebook;
  String? whatsapp;
  String? instagram;
  String? twitter;
  String? website;

  User();




  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    pointsCount = json['points_count'];
    cityId = json['city_id'];
    name = json['name'];
    commercialActivities = json['commercial_activities'];
    mobile = json['mobile'];
    email = json['email'];
    facebook = json['facebook'];
    whatsapp = json['whatsapp'];
    instagram = json['instagram'];
    twitter = json['twitter'];
    website = json['website'];

    rememberToken = json['remember_token'];
    imageProfile = json['image_profile'];
    type = json['type'];
    status = json['status'];
    createdAt = json['created_at'];
    accessToken = json['access_token'];
    followMeCount = json['follow_me_count'];
    city = json['city'] != null ? new City.fromJson(json['city']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['points_count'] = this.pointsCount;
    data['city_id'] = this.cityId;
    data['name'] = this.name;
    data['commercial_activities'] = this.commercialActivities;
    data['mobile'] = this.mobile;
    data['email'] = this.email;
    data['remember_token'] = this.rememberToken;
    data['image_profile'] = this.imageProfile;
    data['facebook'] = this.facebook;
    data['whatsapp'] = this.whatsapp;
    data['instagram'] = this.instagram;
    data['twitter'] = this.twitter;
    data['type'] = this.type;
    data['status'] = this.status;
    data['created_at'] = this.createdAt;
    data['access_token'] = this.accessToken;
    data['follow_me_count'] = this.followMeCount;
    data['website'] = this.website;
    if (this.city != null) {
      data['city'] = this.city!.toJson();
    }
    return data;
  }
}

class City {
  int? id;
  int? countryId;
  String? status;
  String? createdAt;
  String? name;

  City();

  City.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    countryId = json['country_id'];
    status = json['status'];
    createdAt = json['created_at'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['country_id'] = this.countryId;
    data['status'] = this.status;
    data['created_at'] = this.createdAt;
    data['name'] = this.name;
    return data;
  }
}

class Followers {
  int? id;
  int? followerId;
  int? followedId;
  String? createdAt;

  Advertiser? advertiser;
  Follower? follower;



  Followers.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    followerId = json['follower_id'];
    followedId = json['followed_id'];
    createdAt = json['created_at'];

    advertiser = json['advertiser'] != null
        ? new Advertiser.fromJson(json['advertiser'])
        : null;
    follower = json['follower'] != null
        ? new Follower.fromJson(json['follower'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['follower_id'] = this.followerId;
    data['followed_id'] = this.followedId;
    data['created_at'] = this.createdAt;

    if (this.advertiser != null) {
      data['advertiser'] = this.advertiser!.toJson();
    }
    if (this.follower != null) {
      data['follower'] = this.follower!.toJson();
    }
    return data;
  }
}

class Advertiser {
  int? id;
  int? pointsCount;
  int? cityId;
  String? name;
  String? commercialActivities;
  String? mobile;
  String? website;
  String? email;
  String? twitter;
  String? instagram;
  String? whatsapp;
  String? facebook;
  String? latitude;
  String? longitude;
  Null? rememberToken;
  String? imageProfile;
  String? type;
  String? status;
  String? createdAt;
  int? followMeCount;
  City? city;
  Advertiser();







  Advertiser.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    pointsCount = json['points_count'];
    cityId = json['city_id'];
    name = json['name'];
    commercialActivities = json['commercial_activities'];
    mobile = json['mobile'];
    email = json['email'];
    facebook = json['facebook'];
    whatsapp = json['whatsapp'];
    twitter = json['twitter'];
    instagram = json['instagram'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    rememberToken = json['remember_token'];
    imageProfile = json['image_profile'];
    type = json['type'];
    website = json['website'];
    status = json['status'];
    createdAt = json['created_at'];
    followMeCount = json['follow_me_count'];
    city = json['city'] != null ? new City.fromJson(json['city']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['points_count'] = this.pointsCount;
    data['city_id'] = this.cityId;
    data['facebook'] = this.facebook;
    data['instagram'] = this.instagram;
    data['twitter'] = this.twitter;
    data['whatsapp'] = this.whatsapp;
    data['name'] = this.name;
    data['commercial_activities'] = this.commercialActivities;
    data['mobile'] = this.mobile;
    data['email'] = this.email;
    data['website'] = this.website;
    data['latitude'] = this.latitude;
    data['longitude'] = this.longitude;
    data['remember_token'] = this.rememberToken;
    data['image_profile'] = this.imageProfile;
    data['type'] = this.type;
    data['status'] = this.status;
    data['created_at'] = this.createdAt;
    data['follow_me_count'] = this.followMeCount;
    if (this.city != null) {
      data['city'] = this.city!.toJson();
    }
    return data;
  }
}

class Follower {
  int? id;
  int? pointsCount;
  int? cityId;
  String? name;
  String? commercialActivities;
  String? mobile;
  String? email;
  Null? latitude;
  Null? longitude;
  Null? rememberToken;
  String? imageProfile;
  String? type;
  String? status;
  String? createdAt;
  int? followMeCount;
  City? city;
  Follower();

  Follower.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    pointsCount = json['points_count'];
    cityId = json['city_id'];
    name = json['name'];
    commercialActivities = json['commercial_activities'];
    mobile = json['mobile'];
    email = json['email'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    rememberToken = json['remember_token'];
    imageProfile = json['image_profile'];
    type = json['type'];
    status = json['status'];
    createdAt = json['created_at'];
    followMeCount = json['follow_me_count'];
    city = json['city'] != null ? new City.fromJson(json['city']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['points_count'] = this.pointsCount;
    data['city_id'] = this.cityId;
    data['name'] = this.name;
    data['commercial_activities'] = this.commercialActivities;
    data['mobile'] = this.mobile;
    data['email'] = this.email;
    data['latitude'] = this.latitude;
    data['longitude'] = this.longitude;
    data['remember_token'] = this.rememberToken;
    data['image_profile'] = this.imageProfile;
    data['type'] = this.type;
    data['status'] = this.status;
    data['created_at'] = this.createdAt;
    data['follow_me_count'] = this.followMeCount;
    if (this.city != null) {
      data['city'] = this.city!.toJson();
    }
    return data;
  }
}

